CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  telephone_number VARCHAR(50),
  telephone_visible BOOLEAN,
  avatar_uri TEXT,
  registration_date TIMESTAMP,
  user_rating REAL,
  CONSTRAINT pk_user PRIMARY KEY (user_id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
  CONSTRAINT NOT_EMPTY_EMAIL_AND_NAME CHECK(email <> '' AND user_name <> '')
);

CREATE TABLE IF NOT EXISTS user_address (
  user_id INTEGER NOT NULL,
  country VARCHAR(100) NOT NULL,
  region VARCHAR(100) NOT NULL,
  city_or_settlement VARCHAR(200) NOT NULL,
  city_district VARCHAR(200) NOT NULL,
  street VARCHAR(500) NOT NULL,
  house_number INTEGER,
  CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
  item_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  owner_id INTEGER NOT NULL,
  item_name VARCHAR(255) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  available BOOLEAN,
  rent REAL CHECK(rent >= 0),
  item_rating REAL,
  item_photo_uri TEXT,
  post_date TIMESTAMP,
  CONSTRAINT pk_item PRIMARY KEY (item_id),
  CONSTRAINT fk_owner_id FOREIGN KEY (owner_id) REFERENCES users(user_id) ON DELETE CASCADE
);